### ISSUE TITLE
Game crash related to Honed Metal

### ISSUE THREAD

**Issue by andrewexton373** [ixanza/serenity#11]
**Describe the bug**
I noticed that after I open up one of the crafting menus associated with Honed Metal and then either save or leave a location the game seems to crash a good majority of the time. If I don't interact with these menus the game stays perfectly stable. I used the Maintenance > Repair functionality in the Honed Metal Mod Configuration, but that didn't seem to alleviate the issue.

**To Reproduce**

1. Go to 'Warmaiden's in Whiterun'
2. Talk to 'Ulfberth War-Bear'
3. Select 'I'm in need of your crafting expertise', or any of the other Honed Metal provided options
4. Leave the Building or Save (Both have been problematic for me)

**Expected behavior**
I expected the game not to crash after opening up these Honed Metal menus.

**Screenshots**

**Modlist version**
2.4.0

**Did you add any additional mods?**
Nothing additional added.

**Comment by ixanza** [comment]
Can you grab a crashlog from the overwrite folder / netscriptframework/crashes and share it here or ping me on discord with it. Thanks

**Comment by andrewexton373** [comment]
[Crash_2020_9_13_22-33-19.txt](https://github.com/ixanza/serenity/files/5220998/Crash_2020_9_13_22-33-19.txt)

**Comment by ixanza** [comment]
I can replicate this but I have no idea what causes it. Every time I crash the reason is different. At this point I'm just convinced its something to do with the engine messing up.

**Comment by andrewexton373** [comment]
Gotcha, well for now I'm just avoiding those menus and everything else have been running exceptionally well. Great work!

**Comment by ixanza** [comment]
Honed metal has been removed for now
