### ISSUE TITLE
Error Downloading from Wabbajack Skyrim_Particle_Patch_for_ENB-SSE.zip

### ISSUE THREAD

**Issue by dubdox261** [ixanza/serenity#12]
**Describe the bug**
Unable to download Serenity through Wabbajack, Error on Skyrim_Particle_Patch_for_ENB-SSE.zip 

**To Reproduce**

Download Serenity through Wabbajack

**Expected behavior**
All mods to download correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/71353489/93267473-bc458e80-f779-11ea-83ef-788329fe3396.png)

**Modlist version**
Wabbajack version 2.2.2 
Serinity version 2.4.0

**Did you add any additional mods?**
No

**Comment by CamIsKing** [comment]
Same exact issue.

**Comment by CaptainKindness** [comment]
This is also a thing that is effecting me

**Comment by ixanza** [comment]
Idk why I don’t get emails for these. If you’re on the discord grab it from the pins in the support channel.

**Comment by dubdox261** [comment]
I'm sure I'm missing this this somewhere, but could you post the the discord channel?  Not seeing it anywhere.

**Comment by ixanza** [comment]
The discord is the wabbajack discord (https://discord.gg/wabbajack)

You can also grab the proper file here https://mega.nz/file/VNgVRIxI#OSMEzu6256UIAtMDwjPaJRsIgfRuNQY3pF4qmUkh77U . It has open permissions for redistribution. It'll be fixed next update

**Comment by dubdox261** [comment]
Thanks for the help and quick responses, everything installed successfully.  Sorry for not closing sooner, had to go out of town for work.
