### ISSUE TITLE
Serenity unavailable in Wabbajack

### ISSUE THREAD

**Issue by j-rewerts** [ixanza/serenity#17]
Serenity appears to be unavailable due to 2 mods being missing:
![image](https://user-images.githubusercontent.com/8295080/105609275-0f010980-5d5d-11eb-8813-2fd8dd8154ce.png)
([link](https://www.wabbajack.org/#/modlists/status?machineURL=serenity))

**Comment by ixanza** [comment]
I’m aware of this however I’m in the middle of a huge refactor of the list and am not able to fix this for now
