### ISSUE TITLE
Silver Battlestaff problem

### ISSUE THREAD

**Issue by Fjodik** [ixanza/serenity#19]
**Describe the bug**
Silver Battlestaff model is very zoomed-out in traders' inventory. Same applies partly for silver arrow but the view is much better.

**To Reproduce**
Check the weapon vendor in Riverwood or Whiterun.

**Expected behavior**
Should be much more closer.

**Screenshots**
![ScreenShot267](https://user-images.githubusercontent.com/63248466/107156236-77670200-697d-11eb-8380-b3a3f6783ccb.jpg)
![ScreenShot266](https://user-images.githubusercontent.com/63248466/107156237-78982f00-697d-11eb-86ef-e9352b17c14d.jpg)

**Modlist version**
Beta 1

**Did you add any additional mods?**
No

**Comment by ixanza** [comment]
Not something I can fix sorry. I can't do meshes
