### ISSUE TITLE
Gormlaith Golden-Hilt Black Face Bug

### ISSUE THREAD

**Issue by arielle-allice** [ixanza/serenity#2]
**Describe the bug**
Gormlaith during Alduin's Bane quest has black face in the scene viewed after using the Elder Scroll at the time wound. Found this while testing to make sure the main quest doesn't bug here cause it tends to not work properly a lot of the time.

**To Reproduce**

1. Go to 'coc throatoftheworld01'
2. Do 'setstage mq206 10, spawn in Elder Scroll - Dragon, read elder scroll at the time wound and watch scene.'
 
Alternatively the npc base id of the Gormlaith used in this scene is 000CD9F7. It is only this version of her that is bugged since I checked to see if she was fine in Sovngarde Hall of Heroes.

**Expected behavior**
Gormlaith Golden-Hilt to not have black face.

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.
![gormlaith](https://user-images.githubusercontent.com/69109345/89122515-94e37c80-d4bf-11ea-8f18-7310f89898fe.PNG)

**Modlist version**
Version 2.1.2

**Did you add any additional mods?**
No
![mo2](https://user-images.githubusercontent.com/69109345/89122522-9f057b00-d4bf-11ea-9014-5981a5803d54.PNG)
[loadorder.txt](https://github.com/ixanza/serenity/files/5012082/loadorder.txt)
[modlist.txt](https://github.com/ixanza/serenity/files/5012083/modlist.txt)

**Comment by ixanza** [comment]
Thank you for this super detailed report. I’ll take a look

**Comment by arielle-allice** [comment]
No problem. It's not game breaking or anything but definitely worth a look anyway.

**Comment by ixanza** [comment]
Addressed and fixed. Will be in 2.2.0
