### ISSUE TITLE
Static Butterflies

### ISSUE THREAD

**Issue by Erinious** [ixanza/serenity#20]
**Describe the bug**
Butterflies can sometimes be found staying absolutely still in air. They will fly around for a little bit but then do the landing animation to land right onto absolutely nothing.

**To Reproduce**
As far as I can tell you should be able to just find a butterfly and watch it for a bit. After a while it will "land" but it just looks like it is frozen in mid-air.

1. Go to 'outside Pelagia Farms'
2. Do 'find some butterflies and watch them until they "land"

**Expected behavior**
I expect you will find some butterflies that aren't moving at all.

**Screenshots**
![Butterfly landing in air](https://user-images.githubusercontent.com/78812370/107397609-d1c2a880-6acc-11eb-944b-e5b9cd8aa12d.png)

**Modlist version**
3.1.0

**Did you add any additional mods?**

No

**Comment by ixanza** [comment]
Should be fixed in the next beta
