### ISSUE TITLE
Free horses

### ISSUE THREAD

**Issue by Fjodik** [ixanza/serenity#21]
**Describe the bug**
Some horses from Unique Border Gates mod are free, confirmed with the Talos Pass Gate.

**To Reproduce**
Check the horses at Talos Pass Gate.

**Expected behavior**
Horses should not be freely available.

**Screenshots**
![ScreenShot277](https://user-images.githubusercontent.com/63248466/107977214-077afc00-6fbb-11eb-9b70-41f3395db677.jpg)
![ScreenShot276](https://user-images.githubusercontent.com/63248466/107977218-08139280-6fbb-11eb-8a0d-0a0dd8d75fd7.jpg)
![ScreenShot275](https://user-images.githubusercontent.com/63248466/107977221-09dd5600-6fbb-11eb-945d-e7b81978488d.jpg)

**Modlist version**
Serenity Beta 2

**Did you add any additional mods?**
No

**Comment by ixanza** [comment]
Added an ownership to them in 0.3.0
