### ISSUE TITLE
Cannot recruit Inigo

### ISSUE THREAD

**Issue by Hadrosak1** [ixanza/serenity#22]
**Describe the bug**
Cannot recruit Inigo. He is in Riften dungeon, but only sitting motionlesly, and does not react to interaction (actualy the talk interaction is not even highlighted).

**To Reproduce**
Tried twice with 2 different characters (also reinstalled the modpack). No added mods other than the widescreen ones recomended in the guide.

**Did you add any additional mods?**
Widescreen support ones as per the guide

**Comment by ixanza** [comment]
Not a bug. See Noteworthy mods section and check for Inigo there
