### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Jaheira** [ixanza/serenity#26]
A file was corrupted, Whabbajack would complain it was missing and not start with installation. Ixanza solved the problem by providing this download lin:
https://drive.google.com/file/d/1HDPW6ms-9B6eC8wyQaf4Yz-pknlUF1-y/view?usp=sharing
Replace the corrupted file in your download folder on your pc.

**Comment by ixanza** [comment]
Hello. The file was just updated a day ago. If you're in the wabbajack discord you can get the old file from the serenity support channel there

**Comment by Jaheira** [comment]
Hello,

I tried Discord. Never used it before, I don't get how it works and I
couldn't create an account. Could you help me with a direct link? I hope
that Whabbajack would start when I click on the link that's somewhere on
Discord?

I also tried to load the missing file manually, I found it and then I found
out that I had it already downloaded. I replaced it with the new download,
just in case. I have no idea why the installation in Whabbajack failed.

Is ist possible to skip the download phase and start with installation? I
have downloaded 836 from 836 files, it seems to be complete.

Best regards
Romi

Am Do., 1. Apr. 2021 um 02:37 Uhr schrieb ixanza ***@***.***>:

**Comment by ixanza** [comment]
Here's a mirror . you should be able to continue with this https://drive.google.com/file/d/1HDPW6ms-9B6eC8wyQaf4Yz-pknlUF1-y/view?usp=sharing

**Comment by Jaheira** [comment]
Hello,

I used your link to replace the other file and I also chose  to use the
modlist on my computer drive for installation (for no reason, I don't know
what I am doing). Now the installer works, and tonight I will sneak through
Skyrim and hunt for rabbits.

Thank you very much for your effort and happy easter holydays.
Romi


Am Do., 1. Apr. 2021 um 13:39 Uhr schrieb ixanza ***@***.***>:

**Comment by Jaheira** [comment]
Installation failed again. It did work for a long time but could not be
completed.

I feel like somebody dragged a juicy hot rabbit leg out of my mouth.



Am Do., 1. Apr. 2021 um 13:39 Uhr schrieb ixanza ***@***.***>:
