### ISSUE TITLE
File Hash failed on google drive file

### ISSUE THREAD

**Issue by caldorein1** [ixanza/serenity#27]
(![image](https://user-images.githubusercontent.com/81923986/113516588-ab574180-9540-11eb-98e3-0bed6565b4aa.png))
![image](https://user-images.githubusercontent.com/81923986/113516699-536d0a80-9541-11eb-89d4-23a708c6ff37.png)

AM new really to this so If I am doing it wrong I am sorry. Downloaded List on WabbaJack all files downloaded then failed install. Tried to find file its self and have had no success.

**Comment by ixanza** [comment]
Sorry for being this late. The file was updated and the update from a week ago fixed this.
