### ISSUE TITLE
Installation succeeded, but Skyrim runs vanilla

### ISSUE THREAD

**Issue by Jaheira** [ixanza/serenity#28]
Edit: solved, but I don't know why.

I could complete the installation of Serenity with Wabbajack, but when I start Skyrim in the installation folder/Stock Game/ SkyrimSE.exe, I get vanilla Skyrim without any mods. When I start skse64_loader.exe, I do get a faulty version of the game with a lilac dragon symbol in the start menu, but it crashes after a few seconds.

I tried three times complete installations of Skyrim SE from steam and the modlist with Wabbajack. I had also installed Microsoft Visual C++ upfront and used directories directly created under c:.

I have no idea why there appear no mods in Skyrim.

[Wabbajack.current.log](https://github.com/ixanza/serenity/files/6255105/Wabbajack.current.log)

**Comment by ixanza** [comment]
Sorry for the late response. but did you launch the game from MO2? you're supposed to launch MO2 and then use SKSE from there. Otherwise there will be no mods

**Comment by Jaheira** [comment]
I finally did. I didn't see that part of the installation guide at first
because it is not in the post installation chapter but under the mod
chapter. I didn't read so far since I didn't expect installtation
information there.

Thank you. And please excuse me now, I got to pick a few more snowberrys,
then I'll open a potion store chain across Skyrim, hire an army and save
the world in no time.

Best regards
Romi




Am Montag, 19. April 2021 schrieb ixanza ***@***.***>:
> Sorry for the late response. but did you launch the game from MO2? you're
supposed to launch MO2 and then use SKSE from there. Otherwise there will
be no mods
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/tmE0xw9WifU3UHtMwe4K9NJTcM8v-Au1QOz-IcBNcVl8TGRZq6r1OtBWHNvqYydOjyQ-pII5QKIW_Mie5p-mZNf7GEF2d9bWFbRQ6mE0_4T_pzW1glK9JzCR-T9H3t4tOOxTPEV0LNBRVHeSwQJtNoh0nwml7fnvB7cik_hATLLZwoGcDVjXh5HvLwoxq8vx6vOmFTKR0vBdd9zWoitZQiI8ZB1HaSbQ-p2bZv8ahg=s0-d-e1-ft#https://github.com/notifications/beacon/ALTZZI4INJAE4EMURZ6S3O3TJPX3TA5CNFSM42LU6BBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGEBXJJY.gif>
