### ISSUE TITLE
Legacy of the Dragonborn BadGremlins Collection Issue

### ISSUE THREAD

**Issue by KamiSamaFreak** [ixanza/serenity#29]
**Describe the bug**
Legacy of the Dragonborn BadGremlins Collection (https://www.nexusmods.com/skyrimspecialedition/mods/15092)
Bugs in jars cannot be placed in Legacy if the Dragonborn Museum / are not recognized by Legacy of the dragonborn.

Curiously all other BadGremlins Collection items besides the bugs are added as they should be.

**To Reproduce**

1. Launch SKSE, before starting a new game type: COC WhiterunArcadiasCauldron
2. Check the various bugs in jars, none are tagged with the legacy of the dragonborn "+" sign.

**Expected behavior**
BadGremlins Collection Bug in jars are tagged with the legacy of the dragonborn "+" sign and are placeable in the dragonborn gallery.

**Screenshots**
![ScreenShot296](https://user-images.githubusercontent.com/18635762/115148625-fd738900-a04f-11eb-8355-309c1c9385c7.png)
![ScreenShot297](https://user-images.githubusercontent.com/18635762/115148638-0a907800-a050-11eb-9abb-21c418fd9486.png)
![ScreenShot298](https://user-images.githubusercontent.com/18635762/115148654-1f6d0b80-a050-11eb-8886-513ac378d5d8.png)
![ScreenShot299](https://user-images.githubusercontent.com/18635762/115148659-24ca5600-a050-11eb-91b5-43f49a05b69e.png)
![ScreenShot300](https://user-images.githubusercontent.com/18635762/115148665-2b58cd80-a050-11eb-8da5-a32c16e433da.png)
![ScreenShot301](https://user-images.githubusercontent.com/18635762/115148672-327fdb80-a050-11eb-83fc-8ae69496407b.png)
The Bug in Jar display is there it just does not work.
![ScreenShot302](https://user-images.githubusercontent.com/18635762/115148702-4b888c80-a050-11eb-8824-d0c4aa460860.png)
Fish Display on the otherhand does work.

**Modlist version**
1.3.0

**Did you add any additional mods?**
Gamepad Plus Plus
iEquip
Serio's Cycle Hotkeys

**Comment by KamiSamaFreak** [comment]
![image](https://user-images.githubusercontent.com/18635762/115149526-13834880-a054-11eb-8a7f-3bd98d5a409d.png)
Tiny update showing the patch is installed LOTD patch is installed.

**Comment by ixanza** [comment]
This isn't something I can fix on my own. However, the latest LOTD Patches seem to touch this file so it may be fixed on their end.

**Comment by KamiSamaFreak** [comment]
I'll try the update, not today though tired after work, i'll make an update before the week is over though.
