### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by Firion88** [ixanza/serenity#30]
ENB Series 0.452 is missing and can not be downloaded

Modlist version 1.4.0

**Comment by finnWellers** [comment]
I am running into the same problem. The link "http://enbdev.com/enbseries_skyrimse_v0452.zip" cant be resolved, because the file doesn`t seem to exist on the enbseries website anymore.  The newer, existing, version is v0.454.

**Comment by JanisMittelstaedt** [comment]
Until its fixed: Someone shared the old archive on the wabbajack discord. Worked for me at least :)
