### ISSUE TITLE
LOTD Curators Companion missing

### ISSUE THREAD

**Issue by slessek92** [ixanza/serenity#39]
Hello, I get an installation error for "LOTD Curators Companion". The file isnt available on the GitHub anymore and I cant find it anywhere else.

**Comment by slessek92** [comment]
Fixed it myself. Go to the Requiem discord linked in the Serenity 2 Github readme. In Discord join Serenity group and search for "Curator". There you will find a link to the needed file.

**Comment by loficat** [comment]
Thanks for this, slessek92.  Glad I didn't delete it all.

**Comment by Snicklefritzal** [comment]
> Link for LotD Curator's companion. 
> Please download this exact file and place it directly in your Serenity downloads folder (please do not unzip)
> https://www.nexusmods.com/skyrimspecialedition/mods/38529?tab=files&file_id=210832
