### ISSUE TITLE
no spiders option

### ISSUE THREAD

**Issue by gustlik** [ixanza/serenity#5]
***Request***
Is it possible to add information how to add [Insects Begone - Modularly Removing Spiders and Chaurus](https://www.nexusmods.com/skyrimspecialedition/mods/1190) for people that hates spiders?
I am wondering if it will be OK to add it, and sort by LOOT or additional steps are needed.
Thank you.

**Comment by gustlik** [comment]
Reqtificator asked for path to skyrim.ini. I gave it. After pressing patch button, Reqtificator crashed unfortunately.
Message suggests that there should be a log file in ...\serenity\mods\Requiem - The Roleplaying Overhaul\SkyProc Patchers\Requiem\ but there are no log files at all. What would you suggest?

**Comment by ixanza** [comment]
Running the reqtificator for the first time on SSE may be challenging. https://www.reddit.com/r/skyrimrequiem/comments/hkuj7s/requiem_sse_megathread/ has some info specific to running requiem on SSE including getting the reqtificator to work.

**Comment by gustlik** [comment]
thanks. will try it.
BTW when do you plan to push new release? In changelog you mentioned that there is one that is not released yet. https://github.com/ixanza/serenity/blob/master/CHANGELOG.md

**Comment by ixanza** [comment]
Yep that’s coming likely in the next 12 hours

**Comment by gustlik** [comment]
Hi,
I updated the mod list to play again but it seems that there were some changes eg I can't find Reqtificator anywhere. Could you provide short update how to add mode like one of mentioned earlier or https://www.nexusmods.com/skyrimspecialedition/mods/37319?tab=files (that seems to be updated). thank you
