### ISSUE TITLE
Autosave not working

### ISSUE THREAD

**Issue by FISSNOC** [ixanza/serenity#6]
**Describe the bug**
Auto saves are not working in my game. I followed all instructions in readme, and went into settings to check the boxes to autosave at certain times. Options are to autosave at travel, rest, and wait. All three boxes are checked but the game does not autosave ever. I keep losing progress because I'm so used to playing with autosaves. Please fix if you can.

**To Reproduce**

1. Go to "Esc">Settings>Gameplay>check boxes for autosave conditions

**Expected behavior**
The game to autosave when these things happen

**Modlist version**
I'm not sure. Whatever downloads on wabbajack.

**Did you add any additional mods?**
I have not added any additional mods

**Comment by ixanza** [comment]
I’ll enable autosaves next update which should be in a week. Wont be able to this week

**Comment by ixanza** [comment]
Should be there in 2.4
