### ISSUE TITLE
Wabberjack Serenity cannot download a file

### ISSUE THREAD

**Issue by piotress** [ixanza/serenity#7]
**Describe the bug**
When running the Wabberjack install system it halts with an error when trying to download "enbseries_skyrimse_v0437.zip". When going to the link the ENB site comes up with this message:

**_Welcome to ENBSeries project. This is the trap page for bots and protection against hot linking._**

**To Reproduce**
Run the Wabberjack installer and wait for it to come up with the message about not being able to download the file.

**Modlist version**
Update 2.3

**Did you add any additional mods?**

**Comment by ixanza** [comment]
Update wabbajack please. The 2.2.1.7 version was made to fix this.
