### ISSUE TITLE
Unreqtified Armor

### ISSUE THREAD

**Issue by daffodilian** [ixanza/serenity#8]
**Describe the bug**
Silver Hand medium armor does not have requiem armor values

**To Reproduce**

2. Do '...'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, take a screenshot of `You are Here` MCM Option from DynDOLOD as well as a screenshot of the world map.

![ScreenShot69 - Copy](https://user-images.githubusercontent.com/63564258/92025351-68748780-ed2d-11ea-83ce-bfb5c4e2dd6d.png)
![ScreenShot68 - Copy](https://user-images.githubusercontent.com/63564258/92025354-6a3e4b00-ed2d-11ea-9dd4-2fc664502b30.png)

**Modlist version**
Do not say latest
2.3.0latest
**Did you add any additional mods?**

**Comment by ixanza** [comment]
ah fuck i forgot about this LOL

**Comment by ixanza** [comment]
Fixed
